#!/usr/bin/env python3
#
# Copyright (C) 2016 James Murphy
# Licensed under the GPL version 2 only
#
# A battery indicator blocklet script for i3blocks

import re
from subprocess import check_output

status = check_output(['acpi'], universal_newlines=True)

if not status:
    # stands for no battery found
    fulltext = "<span color='red'><span font='FontAwesome'>\uf00d \uf240</span></span>"
    percentleft = 100
else:
    # if there is more than one battery in one laptop, the percentage left is 
    # available for each battery separately, although state and remaining 
    # time for overall block is shown in the status of the first battery 
    batteries = status.split("\n")
    state_batteries=[]
    commasplitstatus_batteries=[]
    percentleft_batteries=[]
    time = ""
    for battery in batteries:
        if battery!='':
            state_batteries.append(battery.split(": ")[1].split(", ")[0])
            commasplitstatus = battery.split(", ")
            if not time:
                time = commasplitstatus[-1].strip()
                # check if it matches a time
                time = re.match(r"(\d+):(\d+)", time)
                if time:
                    time = ":".join(time.groups())
                    timeleft = " ({})".format(time)
                else:
                    timeleft = ""

            p = int(commasplitstatus[1].rstrip("%\n"))
            if p>0:
                percentleft_batteries.append(p)
            commasplitstatus_batteries.append(commasplitstatus)
    state = state_batteries[0]
    commasplitstatus = commasplitstatus_batteries[0]
    if percentleft_batteries:
        percentleft = int(sum(percentleft_batteries)/len(percentleft_batteries))
    else:
        percentleft = 0

    # bar states
    FA_BAR = {
        "empty": "\uf244",
        "quarter": "\uf243",
        "half": "\uf242",
        "three-quarters": "\uf241",
        "full": "\uf240"
        }

    def set_battery_bar(percent):
        if percent < 10:
            bar = FA_BAR["empty"] 
        if percent < 25:
            bar = FA_BAR["quarter"] 
        elif percent < 50:
            bar = FA_BAR["half"] 
        elif percent < 75:
            bar = FA_BAR["three-quarters"] 
        else:
            bar = FA_BAR["full"]
        return "<span font='FontAwesome'>{}</span>".format(bar)
    
    # stands for using battery
    FA_BATTERY = set_battery_bar(percentleft)

    # stands for charging
    FA_LIGHTNING = "<span color='yellow'><span font='FontAwesome'>\uf0e7</span></span>"

    # stands for plugged in
    FA_PLUG = "<span font='FontAwesome'>\uf1e6</span>"

    # stands for unknown status of battery
    FA_QUESTION = "<span font='FontAwesome'>\uf128</span>"

    if state == "Discharging":
        fulltext = FA_BATTERY
    elif state == "Full":
        fulltext = FA_PLUG
    elif state == "Unknown":
        fulltext = FA_QUESTION + " " + FA_BATTERY
    else:
        fulltext = FA_PLUG + " "

print(fulltext)

if percentleft < 10:
    exit(33)
